name: Publish adonai-client

on:
  push:
    branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false && poetry install
    - name: Build and publish
      run: |
        poetry build
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
